FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    uv sync --frozen --no-install-project --no-dev

COPY . .

RUN mkdir -p /app/public

ENV PATH="/app/.venv/bin:$PATH"
ENV SOURCE=0
ENV RTSP_HOST=mmtx
ENV RTSP_PORT=8554

EXPOSE 8080

CMD ["python", "main.py"]
