name: Build and Publish Smart Eye

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lower case owner and repo name
        run: |
          # Переводим название репозитория в нижний регистр и сохраняем в ENV
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 1. СБОРКА FRONTEND ---
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          # Используем нормализованное имя env.REPO_LOWER
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- 2. СБОРКА BACKEND ---
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- 3. СБОРКА MEDIAMTX ---
      - name: Build and push MediaMTX
        uses: docker/build-push-action@v5
        with:
          context: ./mmtx
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}-mmtx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
